version: '{build}'
image: Visual Studio 2017
build_script:
- ps: ./build.ps1
test: off
artifacts:
  - path: 'Releases\**\*'
    name: Squirrel
environment:
  GITHUB_TOKEN:
    secure: y8xmU7TusUNNO/qIJfFO4969iu9jcRmnRtLkpGu9ijTC5n8r+8ccXaJohi1XjzLj
